DROP TABLE IF EXISTS PACKAGE_MANAGER_REGISTRY;
DROP TABLE IF EXISTS PACKAGE_MANAGER_DATA;

CREATE TABLE PACKAGE_MANAGER_DATA (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    KEY_NAME VARCHAR(255) NOT NULL,
    KEY_VALUE VARCHAR(32),
    UNIQUE(KEY_NAME) ON CONFLICT REPLACE
);


CREATE TABLE PACKAGE_MANAGER_REGISTRY (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(255) NOT NULL,
    VERSION VARCHAR(128) NOT NULL,
    KEYWORDS TEXT,
    AUTHOR TEXT,
    AUTHOR_PSEUDO TEXT,
    DESCRIPTION TEXT,
    UNIQUE(NAME) ON CONFLICT REPLACE
);

BEGIN;
INSERT INTO PACKAGE_MANAGER_DATA (KEY_NAME, KEY_VALUE) VALUES ('REGISTRY_CACHE', '0');
COMMIT;
